### ISSUE TITLE
Speed up login // Infer the MarketID

### ISSUE THREAD

**Issue by Goruti** [Varstahl/xbmc#11] opened 2018-01-26 20:34 UTC
Hey, I was wondering why we need to set the country/MarketID in the setting while it should be handled automatically by the request/cookies.

I come up with this piece of code which allow me to login and see the content available in my country (canada)

```
import requests, requests.cookies
from bs4 import BeautifulSoup as soup
import re
import json
import os
import pickle

URL = "https://www.primevideo.com"
headers = {
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36",
    "upgrade-insecure-requests": "1",
    "Cache-Control" : "max-age=0",
    "Accept-Language":"en-US,en"
}

data = {
    "email": <YOUR_EMAIL_ADDRESS>,
    "password":<YOUR_PASSWORD>,
    "rememberMe":"true" 
}

cookies_filename = "~/prime_cookies"

def save_cookies(session, filename):
    if not os.path.isdir(os.path.dirname(filename)):
        return False
    with open(filename, "w') as f:
        f.truncate()
        pickle.dump(session.cookies._cookies, f)


def load_cookies(filename):
    if not os.path.isfile(filename):
        return False

    with open(filename) as f:
        cookies = pickle.load(f)
        if cookies:
            jar = requests.cookies.RequestsCookieJar()
            jar._cookies = cookies
            return jar 
        else:
            return False

with requests.Session() as s:
    cookies = load_cookies(cookies_filename)
    
    if not cookies:
        r = s.get(URL, headers = headers)
        r_soup = soup(r.content, "html5lib")

        signin_url = "{}{}".format(URL, r_soup.find_all(href=re.compile("signin"))[0]["href"])
        headers["Referer"] = URL
        r = s.get(signin_url, headers = headers)
        r_soup = soup(r.content, "html5lib")

        signin_form = r_soup.find_all("form", {"name":"signIn"})[0]
        url_to_sign = signin_form["action"]

        for element in signin_form.find_all("input", {"type":"hidden"}):
            attr_name = element.get("name")
            attr_val = element.get("value")
            if attr_name and attr_val:
                data[attr_name]= attr_val

        r = s.post(url_to_sign, headers = headers, data = data)
    else:
        s.cookies = cookies
        r = s.get(URL, headers = headers)    
        
    save_cookies(s, cookies_filename)
```

Please have a look and let me know if this works for you. In this way we can have a login function for all countries in once :) (Although I am not sure if I missing something here)

We can replace the BeautifulSoup by using regular expression in order to allow the scrip to run faster.

**Comment by Varstahl** [comment] 2018-01-26 21:17
I'm not sure I understand. We don't require market id for login, it's used in a different section. As to the why I didn't do it differently, I just tried to leave the minor possible impact on the original addon, to better merge it at a later date. I switched to request instead of urllib2 solely based on the fact that urllib2 was tanking heavily the performances on primevideo.com.

As for the BS, I tried to not touch as much as the original codebase as possible. Since I can't test amazon.de just as Sandmann can't test primevideo.com, I didn't want to speed up one service and break the other, so I tried to reuse as much code as possible changing as little code as possible.

I'm not too comfortable completely refactorizing Sandmann's code at the moment, but I see where you're coming from though, I'll keep this open as a reminder, but I'd post-pone it until after the merge of this branch with the original addon code.

As for the MarketID, did you mean that we should read the it from the cookies/javascript/wherever, instead of asking them to the user? I'm not sure they're ever set, I might have to look back at it.

**Comment by CGarces** [comment] 2018-01-27 01:10
I think that there is a misunderstanding, the user not enter the `MarketID`, the user enter the prime video area.
@Goruti maybe you are talking about the `primevideo_area` that is part of the settings.
So... @Varstahl it's possible to refactor the code to get the `MarketID` from login, and calculate the `primevideo_area`value from the `MarketID`? (In fact I don't know why the `primevideo_area` is needed if you have `MarketID`)
 
The information are located at id="av-wconf-dv-web-player-cfg" inside a json structure.
So the final user don't need to figure what is the correct value.

**Comment by Varstahl** [comment] 2018-01-27 03:37
Yeah, I guess it's possible. I'll need to check if inferring instead of declaring can cause issues, but I'll check tomorrow.

**Comment by Goruti** [comment] 2018-01-27 04:12
@CGarces @Varstahl , Sorry for the misunderstanding. Yes, as @CGarces mentioned, I was talking (or trying :) ) about **primevideo_area** which we could load it internally.

@Varstahl Agree with you to do not refactor the whole thing by now! Let's make it work first!

**Comment by Varstahl** [comment] 2018-01-27 12:34
@CGarces while in theory it's still a good idea, there's the little problem about multi-language streams not really working. Until we get that right, whatever the problem is, I feel it's a bit of a moot point, it won't work properly for 90% of the userbase.

**Comment by Varstahl** [comment] 2018-01-27 14:53
I gave it a thought, and although it's doable I would need to move several chunks of code around, needlessly complicating the future merge. While it does holds little benefit for the user, it needlessly complicates the code, which I'm not willing to do at the moment.

I'll keep this in mind for the future, together with the streamlining of the login procedures, but for the moment it's a won't fix situation, there are more pressing matters and I don't think we have many reasons to go fix things which aren't broken.

**Closed by Varstahl** 2018-01-27 14:53 UTC
Labels: enhancement

**Comment by CGarces** [comment] 2018-01-27 19:00
Just FYI

To retrieve the information at https://github.com/Varstahl/xbmc/blob/master/plugin.video.amazon-test/default.py#L2174 instead of hardcode it.

```
        jsondata = json.loads(soup.find('script', attrs={'id': 'av-wconf-dv-web-player-cfg'}).text)
        res = re.search(r'ue_furl=\'(.*?)\'', response, flags=re.DOTALL).groups()
        Endpoint = res[0]
        ATVUrl = 'https://atv-ps%s.primevideo.com' % (Endpoint[3:6])
        MarketID = jsondata['playerConfig']['marketplaceId']

```
Of course require more changes and play with global variables, is just an idea

**Comment by Varstahl** [comment] 2018-01-27 21:13
I posted a similar regular expression on the wiki, it's even easier, `"marketplaceId":"([^"]+)"`, to be used after login, in the same way we parse the user's name, and then store/load to disk. But yeah, not scared of that, I'm more concerned about the consequences on multi-user, endpoints, and catalogs.

Btw you can replace this

```
res = re.search(r'ue_furl=\'(.*?)\'', response, flags=re.DOTALL).groups()
Endpoint = res[0]
```

with this

```
Endpoint = re.search(r'ue_furl=\'(.*?)\'', response, flags=re.DOTALL).group(1)
```

Even though, to date, we quite didn't use the API endpoint yet.
