### ISSUE TITLE
primevideo latinamerican

### ISSUE THREAD

**Issue by thetruemachine** [Varstahl/xbmc#17] opened 2018-02-02 03:07 UTC
Excellent work. 
Could you in the not too distant future make it work with primevideo latinamerican?

**Comment by Varstahl** [comment] 2018-02-02 09:04
Duplicate of https://github.com/Sandmann79/xbmc/issues/22, it already does. The update for PrimeVideo support will be pushed in a few days, we are currently fixing the last couple things.

Unless you are aware of bugs that make it currently not work for latinamericans, I'll just assume it does.

**Closed by Varstahl** 2018-02-02 09:04 UTC

**Comment by thetruemachine** [comment] 2018-02-03 02:21
Thanks.
