### ISSUE TITLE
HD contents

### ISSUE THREAD

**Issue by stan86** [Varstahl/xbmc#14] opened 2018-01-28 11:39 UTC
I'm trying your version from Italy, now it seems to work but only for low-resolutions. Setting HD resolutions gives me a blank screen. Is it a limit or am I doing something wrong?

**Comment by Varstahl** [comment] 2018-01-28 13:49
There is a limit in InputStream.Adaptive, where the adaptive doesn't quite work yet. If you go for the automatic settings inside inputstream.adaptive it shuould give you the best resolution by default. If you disable the automatic and go for manual selection, you should be able to pick from about 10 different bitrates, if you can tell me which videos don't work at which bitrate, I might give it a try (I'm italian as well).

There's no hard-cap on our end in regard to HD, as far as I tested all the resolutions were working. The only limit I think I've read is for 4k, not currently supported by IS.A.

**Comment by Varstahl** [comment] 2018-01-28 14:09
I re-tested just in case, but I can confirm that at least up to 1080p it's working without any issues:

![1080p](https://user-images.githubusercontent.com/284077/35483008-15c1b3a4-043d-11e8-9b9f-e1aee400b5a2.jpg)

I've noticed that sometimes the server hiccups a little, maybe some non cached movie take a bit more to download and stream? I'm not sure.

**Comment by Varstahl** [comment] 2018-01-28 14:24
Nevermind, I found a movie with the exact problem you were describing, [Elysium](https://www.primevideo.com/detail/0N4N45OGQW9DPZ4NQN78H2BZA5/). It might be a codec problem, I'm not entirely sure, but if it's not something silly like that, it's some issues with the InputStream.Adaptive itself. I'll try to take a look.

**Comment by stan86** [comment] 2018-01-28 14:39
what's the movie that works instead?

**Comment by Varstahl** [comment] 2018-01-28 14:48
I didn't check many movies, but I tested it on several tv series (mainly cartoons), like [Paw Patrol](https://www.primevideo.com/detail/0T61UDZFGC2PMPNIZF7T0PXR2R). That's the one the screenshot comes from. They were faster to work with while developing, so seeing that 1080p was working fine it didn't even occur to me that some streams could have not. I've tested a couple movies like Elysium, Fight Club and District 9, and they all behave the same.

It's not a problem about the addon per se, there must be something different in the encoding of full fledged movies.

**Comment by stan86** [comment] 2018-01-28 15:03
Paw Patrol works well, something related hdcp?

**Comment by Varstahl** [comment] 2018-01-28 15:28
I'm afraid I can't answer the question. I thought it might be a codec problem, but I just checked the 1920 from Paw Patrol to the 1920 from a random movie: same codec (avc1.640028), same bitrate, same scantype. The only thing that differs is the height, 1080p (16:9) for Paw Patrol, 1040p (24:13) for the movies. Maybe that is what causes the codec to freak out? I don't really know, and I don't know whether the problem is stream related, IS.A related, or Kodi related.

The only thing I know is that by going in the IS.A settings, setting the `Max. Resolution secure decoder` to `Max` and `Stream Selection` to auto, usually gives the best possible quality it can stream. Kodi 18 and IS.A are still under active development, it wouldn't surprise if it was a problem on their end.

**Comment by oomek** [comment] 2018-01-30 00:07
Same here in the UK. I get the lowest quality possible and no audio in every movie I tested.

**Comment by Varstahl** [comment] 2018-01-30 00:12
The lowest quality is due to IS.A being usually set to Manual instead of Auto. It start streaming the first stream it sees, and it's the lowest quality usually. The no audio is quite strange though, you should probably ask Sandmann.

Can't help you there since primevideo.com and amazon.co.uk although working quite the same they don't share the basics.

**Comment by oomek** [comment] 2018-01-30 00:24
I've tried every possible combination in settings, but the maximum video stream resolution I could get is 512x216 and audio stream: unknown. I was so hyped when I saw that you are working on that what Sandman abandoned, but unfortunately it's not meant for me as IS still have some issues and I cannot stand watching movies in the browser without remote control and in 60hz.

**Comment by oomek** [comment] 2018-01-30 00:38
Here is my debug log in case you are interested
https://pastebin.com/raw/kSZAKW1g

Would you possibly try to use some proxy to connect to the amazon.co.uk and check why it's failing to play in 1080p and without audio by any chance?

**Comment by Varstahl** [comment] 2018-01-30 12:33
Apparently I can watch some of it, I've tried just logging in co.uk and it lets me watch something. I'll try to take a look after work.

**Comment by oomek** [comment] 2018-02-02 17:39
Well, I have downloaded your updated addon and copied it over what I've got and I have the sound!
unfortunately still no HD. The maximum resolutions I get are for example:
960x520
960x540
720x576
1088x464
But no full HD unfortunately. I have IS.A set to 0, 0, Max, Max, Auto, All, Off, On

**Comment by Varstahl** [comment] 2018-02-02 18:06
Ok, that's normal then. It's a problem with IS.A probably. If you go to tv series you will probably find out that it works perfectly fine at 1080p. We still don't know why, it might be a problem with aspect ratio, ffmpeg, or something else, but since it's not specifically addon related I'm closing this.

I'll keep you guys updated in case we find something.

**Closed by Varstahl** 2018-02-02 18:06 UTC
Labels: non-issue, question

**Comment by oomek** [comment] 2018-02-09 23:28
I've received the answer on the Kodi forum, regarding that issue. It seems that the streams with better quality have some DRM that is not recognisable by the widevinecdm.dll what you are using. Kodi installs the version 1.4.8.1008, but the latest one is 1.4.8.1070. I've tried to copy it over the old one, but then none of the streams are playing. Kodi throws failed to play error. Is it something that you have control over or is it managed by IS.A?

**Comment by Varstahl** [comment] 2018-02-10 01:27
Not entirely sure, the widevine is downloaded by InputStream.Helper if I'm correct. I'll try checking it out tomorrow.
